//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepair.RemoteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://15.23.6.3:8011/Service.asmx", ConfigurationName="RemoteService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://15.23.6.3:8011/Service.asmx 的元素名称 GetHourValueResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://15.23.6.3:8011/Service.asmx/GetHourValue", ReplyAction="*")]
        DataRepair.RemoteService.GetHourValueResponse GetHourValue(DataRepair.RemoteService.GetHourValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://15.23.6.3:8011/Service.asmx/GetHourValue", ReplyAction="*")]
        System.Threading.Tasks.Task<DataRepair.RemoteService.GetHourValueResponse> GetHourValueAsync(DataRepair.RemoteService.GetHourValueRequest request);
        
        // CODEGEN: 命名空间 http://15.23.6.3:8011/Service.asmx 的元素名称 GetDayValueResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://15.23.6.3:8011/Service.asmx/GetDayValue", ReplyAction="*")]
        DataRepair.RemoteService.GetDayValueResponse GetDayValue(DataRepair.RemoteService.GetDayValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://15.23.6.3:8011/Service.asmx/GetDayValue", ReplyAction="*")]
        System.Threading.Tasks.Task<DataRepair.RemoteService.GetDayValueResponse> GetDayValueAsync(DataRepair.RemoteService.GetDayValueRequest request);
        
        // CODEGEN: 命名空间 http://15.23.6.3:8011/Service.asmx 的元素名称 riqi 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://15.23.6.3:8011/Service.asmx/GetOldDayValue", ReplyAction="*")]
        DataRepair.RemoteService.GetOldDayValueResponse GetOldDayValue(DataRepair.RemoteService.GetOldDayValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://15.23.6.3:8011/Service.asmx/GetOldDayValue", ReplyAction="*")]
        System.Threading.Tasks.Task<DataRepair.RemoteService.GetOldDayValueResponse> GetOldDayValueAsync(DataRepair.RemoteService.GetOldDayValueRequest request);
        
        // CODEGEN: 命名空间 http://15.23.6.3:8011/Service.asmx 的元素名称 riqi 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://15.23.6.3:8011/Service.asmx/GetXianValue", ReplyAction="*")]
        DataRepair.RemoteService.GetXianValueResponse GetXianValue(DataRepair.RemoteService.GetXianValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://15.23.6.3:8011/Service.asmx/GetXianValue", ReplyAction="*")]
        System.Threading.Tasks.Task<DataRepair.RemoteService.GetXianValueResponse> GetXianValueAsync(DataRepair.RemoteService.GetXianValueRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHourValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHourValue", Namespace="http://15.23.6.3:8011/Service.asmx", Order=0)]
        public DataRepair.RemoteService.GetHourValueRequestBody Body;
        
        public GetHourValueRequest() {
        }
        
        public GetHourValueRequest(DataRepair.RemoteService.GetHourValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetHourValueRequestBody {
        
        public GetHourValueRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHourValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHourValueResponse", Namespace="http://15.23.6.3:8011/Service.asmx", Order=0)]
        public DataRepair.RemoteService.GetHourValueResponseBody Body;
        
        public GetHourValueResponse() {
        }
        
        public GetHourValueResponse(DataRepair.RemoteService.GetHourValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://15.23.6.3:8011/Service.asmx")]
    public partial class GetHourValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHourValueResult;
        
        public GetHourValueResponseBody() {
        }
        
        public GetHourValueResponseBody(string GetHourValueResult) {
            this.GetHourValueResult = GetHourValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDayValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDayValue", Namespace="http://15.23.6.3:8011/Service.asmx", Order=0)]
        public DataRepair.RemoteService.GetDayValueRequestBody Body;
        
        public GetDayValueRequest() {
        }
        
        public GetDayValueRequest(DataRepair.RemoteService.GetDayValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDayValueRequestBody {
        
        public GetDayValueRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDayValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDayValueResponse", Namespace="http://15.23.6.3:8011/Service.asmx", Order=0)]
        public DataRepair.RemoteService.GetDayValueResponseBody Body;
        
        public GetDayValueResponse() {
        }
        
        public GetDayValueResponse(DataRepair.RemoteService.GetDayValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://15.23.6.3:8011/Service.asmx")]
    public partial class GetDayValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDayValueResult;
        
        public GetDayValueResponseBody() {
        }
        
        public GetDayValueResponseBody(string GetDayValueResult) {
            this.GetDayValueResult = GetDayValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOldDayValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOldDayValue", Namespace="http://15.23.6.3:8011/Service.asmx", Order=0)]
        public DataRepair.RemoteService.GetOldDayValueRequestBody Body;
        
        public GetOldDayValueRequest() {
        }
        
        public GetOldDayValueRequest(DataRepair.RemoteService.GetOldDayValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://15.23.6.3:8011/Service.asmx")]
    public partial class GetOldDayValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string riqi;
        
        public GetOldDayValueRequestBody() {
        }
        
        public GetOldDayValueRequestBody(string riqi) {
            this.riqi = riqi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOldDayValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOldDayValueResponse", Namespace="http://15.23.6.3:8011/Service.asmx", Order=0)]
        public DataRepair.RemoteService.GetOldDayValueResponseBody Body;
        
        public GetOldDayValueResponse() {
        }
        
        public GetOldDayValueResponse(DataRepair.RemoteService.GetOldDayValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://15.23.6.3:8011/Service.asmx")]
    public partial class GetOldDayValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOldDayValueResult;
        
        public GetOldDayValueResponseBody() {
        }
        
        public GetOldDayValueResponseBody(string GetOldDayValueResult) {
            this.GetOldDayValueResult = GetOldDayValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXianValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXianValue", Namespace="http://15.23.6.3:8011/Service.asmx", Order=0)]
        public DataRepair.RemoteService.GetXianValueRequestBody Body;
        
        public GetXianValueRequest() {
        }
        
        public GetXianValueRequest(DataRepair.RemoteService.GetXianValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://15.23.6.3:8011/Service.asmx")]
    public partial class GetXianValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string riqi;
        
        public GetXianValueRequestBody() {
        }
        
        public GetXianValueRequestBody(string riqi) {
            this.riqi = riqi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXianValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXianValueResponse", Namespace="http://15.23.6.3:8011/Service.asmx", Order=0)]
        public DataRepair.RemoteService.GetXianValueResponseBody Body;
        
        public GetXianValueResponse() {
        }
        
        public GetXianValueResponse(DataRepair.RemoteService.GetXianValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://15.23.6.3:8011/Service.asmx")]
    public partial class GetXianValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetXianValueResult;
        
        public GetXianValueResponseBody() {
        }
        
        public GetXianValueResponseBody(string GetXianValueResult) {
            this.GetXianValueResult = GetXianValueResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : DataRepair.RemoteService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<DataRepair.RemoteService.ServiceSoap>, DataRepair.RemoteService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataRepair.RemoteService.GetHourValueResponse DataRepair.RemoteService.ServiceSoap.GetHourValue(DataRepair.RemoteService.GetHourValueRequest request) {
            return base.Channel.GetHourValue(request);
        }
        
        public string GetHourValue() {
            DataRepair.RemoteService.GetHourValueRequest inValue = new DataRepair.RemoteService.GetHourValueRequest();
            inValue.Body = new DataRepair.RemoteService.GetHourValueRequestBody();
            DataRepair.RemoteService.GetHourValueResponse retVal = ((DataRepair.RemoteService.ServiceSoap)(this)).GetHourValue(inValue);
            return retVal.Body.GetHourValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataRepair.RemoteService.GetHourValueResponse> DataRepair.RemoteService.ServiceSoap.GetHourValueAsync(DataRepair.RemoteService.GetHourValueRequest request) {
            return base.Channel.GetHourValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataRepair.RemoteService.GetHourValueResponse> GetHourValueAsync() {
            DataRepair.RemoteService.GetHourValueRequest inValue = new DataRepair.RemoteService.GetHourValueRequest();
            inValue.Body = new DataRepair.RemoteService.GetHourValueRequestBody();
            return ((DataRepair.RemoteService.ServiceSoap)(this)).GetHourValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataRepair.RemoteService.GetDayValueResponse DataRepair.RemoteService.ServiceSoap.GetDayValue(DataRepair.RemoteService.GetDayValueRequest request) {
            return base.Channel.GetDayValue(request);
        }
        
        public string GetDayValue() {
            DataRepair.RemoteService.GetDayValueRequest inValue = new DataRepair.RemoteService.GetDayValueRequest();
            inValue.Body = new DataRepair.RemoteService.GetDayValueRequestBody();
            DataRepair.RemoteService.GetDayValueResponse retVal = ((DataRepair.RemoteService.ServiceSoap)(this)).GetDayValue(inValue);
            return retVal.Body.GetDayValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataRepair.RemoteService.GetDayValueResponse> DataRepair.RemoteService.ServiceSoap.GetDayValueAsync(DataRepair.RemoteService.GetDayValueRequest request) {
            return base.Channel.GetDayValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataRepair.RemoteService.GetDayValueResponse> GetDayValueAsync() {
            DataRepair.RemoteService.GetDayValueRequest inValue = new DataRepair.RemoteService.GetDayValueRequest();
            inValue.Body = new DataRepair.RemoteService.GetDayValueRequestBody();
            return ((DataRepair.RemoteService.ServiceSoap)(this)).GetDayValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataRepair.RemoteService.GetOldDayValueResponse DataRepair.RemoteService.ServiceSoap.GetOldDayValue(DataRepair.RemoteService.GetOldDayValueRequest request) {
            return base.Channel.GetOldDayValue(request);
        }
        
        public string GetOldDayValue(string riqi) {
            DataRepair.RemoteService.GetOldDayValueRequest inValue = new DataRepair.RemoteService.GetOldDayValueRequest();
            inValue.Body = new DataRepair.RemoteService.GetOldDayValueRequestBody();
            inValue.Body.riqi = riqi;
            DataRepair.RemoteService.GetOldDayValueResponse retVal = ((DataRepair.RemoteService.ServiceSoap)(this)).GetOldDayValue(inValue);
            return retVal.Body.GetOldDayValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataRepair.RemoteService.GetOldDayValueResponse> DataRepair.RemoteService.ServiceSoap.GetOldDayValueAsync(DataRepair.RemoteService.GetOldDayValueRequest request) {
            return base.Channel.GetOldDayValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataRepair.RemoteService.GetOldDayValueResponse> GetOldDayValueAsync(string riqi) {
            DataRepair.RemoteService.GetOldDayValueRequest inValue = new DataRepair.RemoteService.GetOldDayValueRequest();
            inValue.Body = new DataRepair.RemoteService.GetOldDayValueRequestBody();
            inValue.Body.riqi = riqi;
            return ((DataRepair.RemoteService.ServiceSoap)(this)).GetOldDayValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataRepair.RemoteService.GetXianValueResponse DataRepair.RemoteService.ServiceSoap.GetXianValue(DataRepair.RemoteService.GetXianValueRequest request) {
            return base.Channel.GetXianValue(request);
        }
        
        public string GetXianValue(string riqi) {
            DataRepair.RemoteService.GetXianValueRequest inValue = new DataRepair.RemoteService.GetXianValueRequest();
            inValue.Body = new DataRepair.RemoteService.GetXianValueRequestBody();
            inValue.Body.riqi = riqi;
            DataRepair.RemoteService.GetXianValueResponse retVal = ((DataRepair.RemoteService.ServiceSoap)(this)).GetXianValue(inValue);
            return retVal.Body.GetXianValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataRepair.RemoteService.GetXianValueResponse> DataRepair.RemoteService.ServiceSoap.GetXianValueAsync(DataRepair.RemoteService.GetXianValueRequest request) {
            return base.Channel.GetXianValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataRepair.RemoteService.GetXianValueResponse> GetXianValueAsync(string riqi) {
            DataRepair.RemoteService.GetXianValueRequest inValue = new DataRepair.RemoteService.GetXianValueRequest();
            inValue.Body = new DataRepair.RemoteService.GetXianValueRequestBody();
            inValue.Body.riqi = riqi;
            return ((DataRepair.RemoteService.ServiceSoap)(this)).GetXianValueAsync(inValue);
        }
    }
}
