//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgDataGather
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Moni_ImgFiles
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Cate { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public string FullFileName { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
